import { Rule } from './types';

// The base pack: universal AI-tell rules that every profile inherits. Genre packs
// (scripture, and later scientific, technical, fiction) add to this. Rules are
// data; adding one is a data edit, not an engine change. See config-model.md.
export const BASE_PACK_ID = 'base';

// A conservative first batch: distinctive phrases with low false-positive risk in
// devotional prose. More rules land incrementally, and the vocabulary lists grow.
export const BASE_RULES: Rule[] = [
	{
		slug: 'reader-direction',
		packId: BASE_PACK_ID,
		category: 'A',
		severity: 'warning',
		message: 'Reader-direction. Cut it and let the sentence do the work.',
		phrases: [
			'read that again',
			'read that carefully',
			'sit with this',
			'sit with that',
			'let that sink in',
			'take a moment',
		],
	},
	{
		slug: 'throat-clearing',
		packId: BASE_PACK_ID,
		category: 'C',
		severity: 'warning',
		message: 'Throat-clearing. Cut it and start with the claim.',
		phrases: [
			"it's important to note",
			"it's important to recognize",
			"it's worth noting",
			'needless to say',
			'it goes without saying',
		],
	},
	{
		slug: 'hedge-stack',
		packId: BASE_PACK_ID,
		category: 'C',
		severity: 'warning',
		message:
			'Stacked hedge. Say what you mean, or say plainly that you are unsure.',
		phrases: [
			'may perhaps',
			'could potentially',
			'it seems likely that',
			'to some extent',
			'in many ways',
			'generally speaking',
		],
	},
	{
		slug: 'flagged-register',
		packId: BASE_PACK_ID,
		category: 'C',
		severity: 'warning',
		message:
			'Flagged register. Use the plainest word that carries the meaning.',
		phrases: [
			'delve',
			'delves',
			'delved',
			'delving',
			'underscore',
			'underscores',
			'underscored',
			'tapestry',
			'intricate',
			'meticulous',
			'showcase',
			'showcases',
			'showcased',
			'showcasing',
			'leverage',
			'leverages',
			'leveraged',
			'leveraging',
			'seamless',
			'seamlessly',
			'multifaceted',
			'myriad',
			'plethora',
		],
		// Only the words with one plain equivalent. `tapestry`, `intricate`,
		// `meticulous` and `multifaceted` are left without a fix on purpose:
		// the right word depends on the sentence, and a confident wrong
		// suggestion costs the writer their own phrasing.
		replace: {
			delve: 'dig',
			delves: 'digs',
			delved: 'dug',
			delving: 'digging',
			underscore: 'show',
			underscores: 'shows',
			underscored: 'showed',
			showcase: 'show',
			showcases: 'shows',
			showcased: 'showed',
			showcasing: 'showing',
			leverage: 'use',
			leverages: 'uses',
			leveraged: 'used',
			leveraging: 'using',
			seamless: 'smooth',
			seamlessly: 'smoothly',
			myriad: 'many',
			plethora: 'many',
		},
	},
	{
		slug: 'summative-closer',
		packId: BASE_PACK_ID,
		category: 'A',
		severity: 'suggestion',
		message:
			'Summative closer. Delete the sentence that restates the point.',
		phrases: [
			'in this way',
			'in that way',
			'in essence',
			'in short',
			'at its core',
			'taken together',
			'this serves to',
		],
	},
	{
		slug: 'cinematic-opener',
		packId: BASE_PACK_ID,
		category: 'A',
		severity: 'suggestion',
		message: 'Cinematic opener. Open on a specific detail from the source.',
		phrases: [
			'in a world where',
			'picture a scene',
			'imagine a world',
			'consider a world',
		],
	},
	{
		slug: 'hollow-attribution',
		packId: BASE_PACK_ID,
		category: 'D',
		severity: 'warning',
		message:
			'Hollow attribution. Name a source, or make the claim in your own voice.',
		phrases: [
			'scholars note',
			'scholars argue',
			'scholars believe',
			'scholars agree',
			'many have observed',
			'many scholars',
			'it is widely believed',
			'it is often said',
			'it is generally accepted',
			'it is commonly held',
		],
	},
	{
		slug: 'placeholder-memory',
		packId: BASE_PACK_ID,
		category: 'D',
		severity: 'suggestion',
		message: 'Placeholder memory. Replace it with the actual specific.',
		phrases: [
			'there was a season when',
			'there was a time when',
			'there was a moment when',
			'i remember a time',
			'i remember a season',
			'at one point',
			'i found myself',
			'i began to realize',
			'i began to understand',
		],
	},
	{
		slug: 'impact-self-rating',
		packId: BASE_PACK_ID,
		category: 'A',
		severity: 'warning',
		message: 'Rating your own point. Delete it and let the point land.',
		phrases: [
			'the contrast is stark',
			'that landed hard',
			'landed hard for me',
			'it was staggering',
			'utterly devastating',
		],
	},
	{
		slug: 'trailing-participial',
		packId: BASE_PACK_ID,
		category: 'A',
		severity: 'warning',
		message: 'Trailing participial. End at the observation.',
		phrases: [
			', creating',
			', allowing',
			', ensuring',
			', highlighting',
			', underscoring',
			', reflecting',
			', emphasizing',
			', revealing',
			', demonstrating',
			', showcasing',
			', serving as',
			', leaving us',
			', leaving the reader',
		],
	},
];
